version: '3.7'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    # environment:
    #   TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
    #   TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
    #   TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
    #   TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    #   TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
    #   MY_PHONE_NUMBER: ${MY_PHONE_NUMBER}
    # volumes:
    #   - ./:/usr/src/app
    # links:
    #   - db
    # environment:
    #   - DB_HOST=db
    # command: npm start
  # db:
  #   image: mongo
